#!/usr/bin/env python3.7

import boto3

ec2 = boto3.resource('ec2')

# = ec2.create_instances(
        #ImageId="ami-06a0cd9728546d178",
        #MinCount=3,
        #MaxCount=3,
        #InstanceType="t2.micro",
   # )
   
ec2.Instance('i-03f129ba2fa37d33e').stop()
ec2.Instance('i-0bd210745bc1356a7').stop()
ec2.Instance('i-060960b2cb9b1fb2e').stop()


